## Handling Imbalance Dataset

What is an Imbalanced Dataset?

When one class dominates the other.

📌 Example:
95% → Class 0
5% → Class 1

👉 Model may just predict Class 0 always and still get 95% accuracy (misleading ❌)

In [1]:
! pip install numpy pandas

Requirement already satisfied: numpy in c:\users\acer\miniconda3\lib\site-packages (2.4.3)
Requirement already satisfied: pandas in c:\users\acer\miniconda3\lib\site-packages (3.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\miniconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\acer\miniconda3\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\acer\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(24)

n_samples = 1000
class_0_ratio = 0.9

n_class_0 = int(n_samples*class_0_ratio)
n_class_1 = n_samples - n_class_0

In [4]:
n_class_0,n_class_1

(900, 100)

In [10]:
# Creating Dataframe with imbalanced dataset

class_0 = pd.DataFrame({
    "feature_1": np.random.normal(loc=0,scale=1,size=n_class_0),
     "feature_2": np.random.normal(loc=0,scale=1,size=n_class_0),
     "target": [0]*n_class_0
})

class_1 = pd.DataFrame({
    "feature_1": np.random.normal(loc=2,scale=1,size=n_class_1),
     "feature_2": np.random.normal(loc=2,scale=1,size=n_class_1),
     "target": [1]*n_class_1
})

In [11]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [12]:
df.head()

   feature_1  feature_2  target
0   0.966046  -0.941817       0
1   1.766234   1.846968       0
2   0.578521  -0.183151       0
3  -1.340284  -0.419511       0
4  -0.546259  -1.249225       0

In [13]:
df.tail()

     feature_1  feature_2  target
995   2.143183   1.718286       1
996   2.417917   1.575450       1
997   2.973017  -0.143888       1
998   2.057456   1.373405       1
999   1.865144   1.394728       1

In [14]:
df["target"].value_counts()

target
0    900
1    100
Name: count, dtype: int64

#### 🔥 Techniques to Handle Imbalanced Data

##### Oversampling (Increase minority class)

In [15]:
df_minority = df[df["target"]==1]
df_majority = df[df["target"]==0]

In [17]:
! pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\acer\miniconda3\lib\site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\acer\miniconda3\lib\site-packages (from scikit-learn) (1.17.1)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ------ --------------------------------- 1.3/8.0 MB 10.0 MB/s eta 0:00:01
   ------------------ --------------------- 3.7/8.0 MB 9.9 MB/s eta 0:00:01
   ------------------------ --------------- 5.0/8.0 MB 8.8 MB/s eta 0:00:01
   ---------------------------------- ----- 6.8/8.0 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 8.1 MB/s  0:00:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn

   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   ---------------------------------------- 3/3 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 threadpoolctl-3.6.0

In [25]:
from sklearn.utils import resample

df_minority_resampled = resample(
    df_minority,replace=True,
    n_samples=len(df_majority),
    random_state=42
)

In [26]:
df_minority_resampled.shape

(900, 3)

In [27]:
df_upsampled = pd.concat([df_majority,df_minority_resampled])

In [28]:
df_upsampled

     feature_1  feature_2  target
0     0.966046  -0.941817       0
1     1.766234   1.846968       0
2     0.578521  -0.183151       0
3    -1.340284  -0.419511       0
4    -0.546259  -1.249225       0
..         ...        ...     ...
952   2.716805   0.423425       1
965   1.862894   3.251101       1
976   3.673115   1.251838       1
942   3.563525   3.184646       1
974   3.093062   2.916969       1

[1800 rows x 3 columns]

In [29]:
df_upsampled["target"].value_counts()

target
0    900
1    900
Name: count, dtype: int64